/**
 * Schematic equipment glyphs for the Floor Twin canvas.
 *
 * Stations used to be identical rectangles, so the floor read as a flow chart
 * rather than a plant: nothing distinguished a stacking robot from a buffer
 * rack except the text underneath it. Each station now draws the *shape of the
 * machine that stands there* — an articulated arm, a laser head, a gantry
 * portal, a stack of prismatic cells.
 *
 * Everything here is drawn in code rather than loaded as an image, which keeps
 * the glyphs crisp at any zoom, lets them follow the light/dark theme and the
 * live status colour, and adds nothing to the bundle.
 *
 * ── Authoring contract ────────────────────────────────────────────────────
 * Every glyph draws inside a 100 × 100 box centred on the origin, so it works
 * in coordinates from -50 to +50 and never needs to know the station's real
 * size. `drawEquipmentGlyph` handles the translate and scale.
 */

export type EquipmentKind =
  | 'robot_arm'
  | 'gantry'
  | 'laser'
  | 'plasma'
  | 'press'
  | 'vision'
  | 'tester'
  | 'cycler'
  | 'sorter'
  | 'dispenser'
  | 'fastener'
  | 'harness'
  | 'controller'
  | 'seal'
  | 'busbar'
  | 'cell_buffer'
  | 'cell_stack'
  | 'pack'
  | 'tray'
  | 'rack'
  | 'dock'
  | 'container'
  | 'coldplate'
  | 'reject';

export interface GlyphPalette {
  /** Machine body outline. */
  stroke: string;
  /** Machine body fill. */
  body: string;
  /** Live status colour — beams, indicators, moving parts. */
  accent: string;
  /** Secondary detail: floor plates, rails, shadows. */
  detail: string;
}

/**
 * Chooses the glyph for a station.
 *
 * Matched on the station id first — those are generated by `buildFactoryModel`
 * and are stable — then on wording in the label, so a station renamed in the
 * census still lands on a sensible shape rather than falling back to a box.
 */
export function classifyStation(
  id: string,
  label: string,
  nodeType: 'IO' | 'M' | 'B',
  unit = ''
): EquipmentKind {
  const l = label.toLowerCase();

  // --- id prefixes: the generated parallel blocks and fixed stations ---
  if (id.startsWith('CY_')) return 'cycler';
  if (id.startsWith('S_BOT_')) return 'robot_arm';
  if (id.startsWith('OCV_')) return 'tester';
  if (id.startsWith('W_CLN_')) return 'laser';
  if (id.startsWith('W_L_')) return 'laser';
  if (id.startsWith('W_FPC_')) return 'busbar';
  if (id.startsWith('W_CCD_')) return 'vision';

  // --- Buffers hold things; they do not process them. ---
  // Classify a buffer by what is stacked in it, never by the process words in
  // its name — otherwise "Pre-Weld Cell Stack Buffer" draws a laser welder and
  // "Clean Buffer" draws a plasma cleaner, when both are simply racks of banded
  // cell stacks waiting their turn.
  if (nodeType === 'B') {
    if (l.includes('reject') || l.includes('quarantine') || l.includes('defect')) return 'reject';
    return classifyByUnit(unit, 'rack');
  }

  // --- wording, most specific first ---
  if (l.includes('gantry') || l.includes('crane')) return 'gantry';
  if (l.includes('plasma')) return 'plasma';
  if (l.includes('laser') || l.includes('weld')) return 'laser';
  if (l.includes('vision') || l.includes('inspection') || l.includes('bead')) return 'vision';
  if (l.includes('press') || l.includes('compress') || l.includes('banding')) return 'press';
  if (l.includes('dispenser') || l.includes('paste') || l.includes('tim')) return 'dispenser';
  if (l.includes('fasten') || l.includes('structural')) return 'fastener';
  if (l.includes('harness') || l.includes('hv/lv') || l.includes('cable')) return 'harness';
  if (l.includes('bms') || l.includes('controller')) return 'controller';
  if (l.includes('seal') || l.includes('cover')) return 'seal';
  if (l.includes('busbar')) return 'busbar';
  if (l.includes('gateway') || l.includes('sort') || l.includes('quality gate')) return 'sorter';
  if (l.includes('reject') || l.includes('quarantine') || l.includes('defect')) return 'reject';
  if (l.includes('container') || l.includes('staging yard') || l.includes('cabinet')) return 'container';
  if (l.includes('cold plate') || l.includes('cooling')) return 'coldplate';
  if (l.includes('leak') || l.includes('hipot') || l.includes('test') || l.includes('cycler')) return 'tester';
  if (l.includes('robot') || l.includes('manipulator') || l.includes('depalletizer') || l.includes('marriage'))
    return 'robot_arm';
  if (l.includes('unloader') || l.includes('tray')) return 'tray';
  if (l.includes('dock') || l.includes('delivery')) return 'dock';
  if (l.includes('racking') || l.includes('store')) return 'rack';

  // --- fall back on what the station holds ---
  if (l.includes('pack')) return 'pack';
  if (l.includes('cell stack') || l.includes('stack')) return 'cell_stack';
  if (l.includes('cell')) return 'cell_buffer';

  if (nodeType === 'IO') return classifyByUnit(unit === 'Cells' ? '' : unit, 'dock');
  return 'robot_arm';
}

/** What a station holds, when its name does not say what it is. */
function classifyByUnit(unit: string, fallback: EquipmentKind): EquipmentKind {
  const u = unit.toLowerCase();
  if (u.includes('stack')) return 'cell_stack';
  if (u.includes('pack')) return 'pack';
  if (u.includes('tray')) return 'tray';
  if (u.includes('container')) return 'container';
  if (u.includes('rack')) return 'rack';
  if (u.includes('cell')) return 'cell_buffer';
  return fallback;
}

// ---------------------------------------------------------------------------
// Drawing primitives, all in the -50..+50 authoring space
// ---------------------------------------------------------------------------

const path = (ctx: CanvasRenderingContext2D, pts: [number, number][], close = false) => {
  ctx.beginPath();
  pts.forEach(([x, y], i) => (i === 0 ? ctx.moveTo(x, y) : ctx.lineTo(x, y)));
  if (close) ctx.closePath();
};

const strokePath = (ctx: CanvasRenderingContext2D, pts: [number, number][], close = false) => {
  path(ctx, pts, close);
  ctx.stroke();
};

const box = (ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, fill?: string) => {
  if (fill) {
    ctx.fillStyle = fill;
    ctx.fillRect(x, y, w, h);
  }
  ctx.strokeRect(x, y, w, h);
};

const dot = (ctx: CanvasRenderingContext2D, x: number, y: number, r: number, fill: string) => {
  ctx.fillStyle = fill;
  ctx.beginPath();
  ctx.arc(x, y, r, 0, Math.PI * 2);
  ctx.fill();
};

/** The floor plinth most fixed machines stand on — grounds the shape. */
const plinth = (ctx: CanvasRenderingContext2D, p: GlyphPalette, halfWidth = 34) => {
  ctx.fillStyle = p.detail;
  ctx.fillRect(-halfWidth, 34, halfWidth * 2, 8);
};

// ---------------------------------------------------------------------------
// The glyphs
// ---------------------------------------------------------------------------

type GlyphFn = (ctx: CanvasRenderingContext2D, p: GlyphPalette, phase: number) => void;

/**
 * `phase` runs 0 → 1 and repeats. Only stations that are actually working are
 * given a moving phase, so a glowing beam or a swinging arm means the station
 * is running, not merely that the canvas is animating.
 */
const GLYPHS: Record<EquipmentKind, GlyphFn> = {
  // Six-axis articulated manipulator: pedestal, shoulder, two links, gripper.
  robot_arm: (ctx, p, phase) => {
    plinth(ctx, p, 26);
    ctx.fillStyle = p.body;
    ctx.fillRect(-14, 14, 28, 22);
    ctx.strokeRect(-14, 14, 28, 22);

    const swing = Math.sin(phase * Math.PI * 2) * 0.35;
    const shoulder: [number, number] = [0, 12];
    const elbow: [number, number] = [0 + Math.sin(swing - 0.6) * 30, 12 - Math.cos(swing - 0.6) * 30];
    const wrist: [number, number] = [elbow[0] + Math.sin(swing + 0.9) * 26, elbow[1] - Math.cos(swing + 0.9) * 26];

    ctx.lineJoin = 'round';
    ctx.lineCap = 'round';
    const upper = ctx.lineWidth;
    ctx.lineWidth = upper * 2.4;
    strokePath(ctx, [shoulder, elbow]);
    ctx.lineWidth = upper * 1.7;
    strokePath(ctx, [elbow, wrist]);
    ctx.lineWidth = upper;

    // Gripper jaws
    const gx = wrist[0];
    const gy = wrist[1];
    ctx.strokeStyle = p.accent;
    strokePath(ctx, [[gx - 7, gy - 6], [gx - 7, gy + 2]]);
    strokePath(ctx, [[gx + 7, gy - 6], [gx + 7, gy + 2]]);
    ctx.strokeStyle = p.stroke;
    dot(ctx, shoulder[0], shoulder[1], 4, p.accent);
    dot(ctx, elbow[0], elbow[1], 3, p.detail);
  },

  // Twin-rail portal crane with a hoist that tracks across the span.
  gantry: (ctx, p, phase) => {
    strokePath(ctx, [[-40, -30], [-40, 36]]);
    strokePath(ctx, [[40, -30], [40, 36]]);
    ctx.fillStyle = p.body;
    ctx.fillRect(-44, -34, 88, 12);
    ctx.strokeRect(-44, -34, 88, 12);

    const tx = Math.sin(phase * Math.PI * 2) * 28;
    ctx.fillStyle = p.accent;
    ctx.fillRect(tx - 8, -22, 16, 8);
    ctx.strokeStyle = p.stroke;
    strokePath(ctx, [[tx, -14], [tx, 8]]);
    ctx.fillStyle = p.body;
    ctx.fillRect(tx - 12, 8, 24, 14);
    ctx.strokeRect(tx - 12, 8, 24, 14);
    plinth(ctx, p, 44);
  },

  // Laser head over the work surface, with a beam cone and focal spot.
  laser: (ctx, p, phase) => {
    ctx.fillStyle = p.body;
    ctx.fillRect(-16, -38, 32, 26);
    ctx.strokeRect(-16, -38, 32, 26);
    strokePath(ctx, [[-8, -12], [-5, 2], [5, 2], [8, -12]], true);

    const hot = 0.45 + Math.abs(Math.sin(phase * Math.PI * 2)) * 0.55;
    ctx.globalAlpha = hot;
    ctx.fillStyle = p.accent;
    path(ctx, [[-5, 2], [5, 2], [11, 26], [-11, 26]], true);
    ctx.fill();
    ctx.globalAlpha = 1;

    dot(ctx, 0, 26, 4, p.accent);
    ctx.fillStyle = p.detail;
    ctx.fillRect(-30, 28, 60, 8);
    ctx.strokeRect(-30, 28, 60, 8);
  },

  // Atmospheric plasma nozzle with an ionised plume.
  plasma: (ctx, p, phase) => {
    ctx.fillStyle = p.body;
    ctx.fillRect(-12, -38, 24, 22);
    ctx.strokeRect(-12, -38, 24, 22);
    strokePath(ctx, [[-7, -16], [-3, -2], [3, -2], [7, -16]], true);

    ctx.strokeStyle = p.accent;
    const w = ctx.lineWidth;
    ctx.lineWidth = w * 0.8;
    for (let i = -2; i <= 2; i++) {
      const drift = Math.sin(phase * Math.PI * 2 + i) * 3;
      strokePath(ctx, [[i * 4, 0], [i * 7 + drift, 24]]);
    }
    ctx.lineWidth = w;
    ctx.strokeStyle = p.stroke;
    ctx.fillStyle = p.detail;
    ctx.fillRect(-28, 26, 56, 8);
    ctx.strokeRect(-28, 26, 56, 8);
  },

  // Hydraulic compression press: ram descends onto the bed.
  press: (ctx, p, phase) => {
    ctx.fillStyle = p.body;
    ctx.fillRect(-34, -40, 68, 12);
    ctx.strokeRect(-34, -40, 68, 12);
    strokePath(ctx, [[-30, -28], [-30, 34]]);
    strokePath(ctx, [[30, -28], [30, 34]]);

    const travel = (Math.sin(phase * Math.PI * 2) + 1) / 2;
    const ramY = -14 + travel * 20;
    ctx.strokeStyle = p.accent;
    const w = ctx.lineWidth;
    ctx.lineWidth = w * 2;
    strokePath(ctx, [[0, -28], [0, ramY]]);
    ctx.lineWidth = w;
    ctx.strokeStyle = p.stroke;
    ctx.fillStyle = p.accent;
    ctx.fillRect(-22, ramY, 44, 10);
    ctx.strokeRect(-22, ramY, 44, 10);

    ctx.fillStyle = p.detail;
    ctx.fillRect(-26, 24, 52, 12);
    ctx.strokeRect(-26, 24, 52, 12);
  },

  // Machine-vision camera on a stand with an inspection cone.
  vision: (ctx, p, phase) => {
    ctx.fillStyle = p.body;
    ctx.fillRect(-18, -36, 36, 22);
    ctx.strokeRect(-18, -36, 36, 22);
    ctx.fillStyle = p.detail;
    ctx.fillRect(-8, -14, 16, 8);
    ctx.strokeRect(-8, -14, 16, 8);

    ctx.globalAlpha = 0.28 + Math.abs(Math.sin(phase * Math.PI * 2)) * 0.34;
    ctx.fillStyle = p.accent;
    path(ctx, [[-8, -6], [8, -6], [24, 24], [-24, 24]], true);
    ctx.fill();
    ctx.globalAlpha = 1;

    dot(ctx, 12, -30, 3.5, p.accent);
    ctx.fillStyle = p.detail;
    ctx.fillRect(-30, 24, 60, 8);
    ctx.strokeRect(-30, 24, 60, 8);
  },

  // Bench instrument: display with a live trace, and probe leads.
  tester: (ctx, p, phase) => {
    ctx.fillStyle = p.body;
    ctx.fillRect(-34, -26, 68, 44);
    ctx.strokeRect(-34, -26, 68, 44);

    ctx.fillStyle = p.detail;
    ctx.fillRect(-27, -19, 54, 24);
    ctx.strokeRect(-27, -19, 54, 24);

    ctx.strokeStyle = p.accent;
    const w = ctx.lineWidth;
    ctx.lineWidth = w * 0.9;
    ctx.beginPath();
    for (let i = 0; i <= 24; i++) {
      const x = -25 + i * (50 / 24);
      const y = -7 + Math.sin(phase * Math.PI * 2 + i * 0.55) * 8;
      i === 0 ? ctx.moveTo(x, y) : ctx.lineTo(x, y);
    }
    ctx.stroke();
    ctx.lineWidth = w;
    ctx.strokeStyle = p.stroke;

    dot(ctx, -24, 12, 3, p.accent);
    dot(ctx, -14, 12, 3, p.detail);
    strokePath(ctx, [[8, 18], [8, 32]]);
    strokePath(ctx, [[20, 18], [20, 32]]);
    plinth(ctx, p, 36);
  },

  // Battery cycler cabinet: channel bays with charge-level bars.
  cycler: (ctx, p, phase) => {
    ctx.fillStyle = p.body;
    ctx.fillRect(-30, -38, 60, 74);
    ctx.strokeRect(-30, -38, 60, 74);

    for (let row = 0; row < 4; row++) {
      const y = -30 + row * 17;
      ctx.fillStyle = p.detail;
      ctx.fillRect(-23, y, 46, 11);
      const level = (Math.sin(phase * Math.PI * 2 + row * 1.3) + 1) / 2;
      ctx.fillStyle = p.accent;
      ctx.fillRect(-23, y, 46 * (0.25 + level * 0.75), 11);
      ctx.strokeRect(-23, y, 46, 11);
    }
    ctx.fillStyle = p.detail;
    ctx.fillRect(-30, 36, 60, 6);
  },

  // Diverter gateway: one lane in, two lanes out.
  sorter: (ctx, p, phase) => {
    ctx.fillStyle = p.detail;
    ctx.fillRect(-42, -6, 40, 12);
    ctx.strokeRect(-42, -6, 40, 12);

    ctx.fillStyle = p.body;
    path(ctx, [[-4, -18], [20, -18], [20, 18], [-4, 18]], true);
    ctx.fill();
    ctx.stroke();

    const flip = Math.sin(phase * Math.PI * 2) > 0;
    ctx.strokeStyle = p.accent;
    const w = ctx.lineWidth;
    ctx.lineWidth = w * 1.8;
    strokePath(ctx, [[2, 0], [16, flip ? -12 : 12]]);
    ctx.lineWidth = w;
    ctx.strokeStyle = p.stroke;

    ctx.fillStyle = p.detail;
    ctx.fillRect(24, -26, 20, 12);
    ctx.strokeRect(24, -26, 20, 12);
    ctx.fillRect(24, 14, 20, 12);
    ctx.strokeRect(24, 14, 20, 12);
    plinth(ctx, p, 30);
  },

  // Gantry-mounted dispensing nozzle laying a bead.
  dispenser: (ctx, p, phase) => {
    ctx.fillStyle = p.body;
    ctx.fillRect(-10, -40, 20, 20);
    ctx.strokeRect(-10, -40, 20, 20);
    strokePath(ctx, [[-6, -20], [-2, -6], [2, -6], [6, -20]], true);

    const bead = (Math.sin(phase * Math.PI * 2) + 1) / 2;
    ctx.strokeStyle = p.accent;
    const w = ctx.lineWidth;
    ctx.lineWidth = w * 1.4;
    strokePath(ctx, [[0, -6], [0, 12]]);
    ctx.beginPath();
    for (let i = 0; i <= 16; i++) {
      const t = i / 16;
      const x = -24 + t * 48;
      const y = 16 + Math.sin(t * Math.PI * 3) * 4;
      i === 0 ? ctx.moveTo(x, y) : ctx.lineTo(x, y);
    }
    ctx.globalAlpha = 0.4 + bead * 0.6;
    ctx.stroke();
    ctx.globalAlpha = 1;
    ctx.lineWidth = w;
    ctx.strokeStyle = p.stroke;

    ctx.fillStyle = p.detail;
    ctx.fillRect(-30, 24, 60, 8);
    ctx.strokeRect(-30, 24, 60, 8);
  },

  // Nutrunner spindle over a bolt pattern.
  fastener: (ctx, p, phase) => {
    ctx.fillStyle = p.body;
    ctx.fillRect(-12, -40, 24, 24);
    ctx.strokeRect(-12, -40, 24, 24);
    strokePath(ctx, [[0, -16], [0, 2]]);

    const spin = phase * Math.PI * 2;
    ctx.save();
    ctx.translate(0, 8);
    ctx.rotate(spin);
    ctx.strokeStyle = p.accent;
    path(
      ctx,
      Array.from({ length: 6 }, (_, i): [number, number] => {
        const a = (i / 6) * Math.PI * 2;
        return [Math.cos(a) * 9, Math.sin(a) * 9];
      }),
      true
    );
    ctx.stroke();
    ctx.restore();
    ctx.strokeStyle = p.stroke;

    ctx.fillStyle = p.detail;
    ctx.fillRect(-28, 22, 56, 12);
    ctx.strokeRect(-28, 22, 56, 12);
    dot(ctx, -18, 28, 2.5, p.stroke);
    dot(ctx, 18, 28, 2.5, p.stroke);
  },

  // HV/LV loom: connector blocks joined by routed cable.
  harness: (ctx, p, phase) => {
    ctx.fillStyle = p.body;
    ctx.fillRect(-40, -12, 18, 24);
    ctx.strokeRect(-40, -12, 18, 24);
    ctx.fillRect(22, -12, 18, 24);
    ctx.strokeRect(22, -12, 18, 24);

    ctx.strokeStyle = p.accent;
    const w = ctx.lineWidth;
    ctx.lineWidth = w * 1.6;
    ctx.beginPath();
    ctx.moveTo(-22, -4);
    ctx.bezierCurveTo(-6, -30, 6, 22, 22, -4);
    ctx.stroke();
    ctx.lineWidth = w * 1.2;
    ctx.strokeStyle = p.detail;
    ctx.beginPath();
    ctx.moveTo(-22, 6);
    ctx.bezierCurveTo(-6, 28, 6, -18, 22, 6);
    ctx.stroke();
    ctx.lineWidth = w;
    ctx.strokeStyle = p.stroke;

    const pulse = Math.abs(Math.sin(phase * Math.PI * 2));
    dot(ctx, -31, 0, 3 + pulse * 1.5, p.accent);
    dot(ctx, 31, 0, 3, p.detail);
    plinth(ctx, p, 32);
  },

  // BMS controller board: PCB with a processor and pin headers.
  controller: (ctx, p, phase) => {
    ctx.fillStyle = p.body;
    ctx.fillRect(-34, -26, 68, 52);
    ctx.strokeRect(-34, -26, 68, 52);

    ctx.fillStyle = p.detail;
    ctx.fillRect(-12, -10, 24, 22);
    ctx.strokeRect(-12, -10, 24, 22);

    ctx.strokeStyle = p.detail;
    for (let i = 0; i < 4; i++) {
      strokePath(ctx, [[-12, -6 + i * 6], [-26, -6 + i * 6]]);
      strokePath(ctx, [[12, -6 + i * 6], [26, -6 + i * 6]]);
    }
    ctx.strokeStyle = p.stroke;

    const blink = Math.sin(phase * Math.PI * 2) > 0;
    dot(ctx, -24, -18, 3, blink ? p.accent : p.detail);
    dot(ctx, -15, -18, 3, blink ? p.detail : p.accent);
    for (let i = 0; i < 7; i++) dot(ctx, -21 + i * 7, 20, 2, p.detail);
  },

  // Lid press sealing a pack case, with a gasket bead.
  seal: (ctx, p, phase) => {
    const travel = (Math.sin(phase * Math.PI * 2) + 1) / 2;
    ctx.fillStyle = p.body;
    ctx.fillRect(-32, -38, 64, 10);
    ctx.strokeRect(-32, -38, 64, 10);

    const lidY = -20 + travel * 12;
    ctx.fillStyle = p.accent;
    ctx.fillRect(-26, lidY, 52, 8);
    ctx.strokeStyle = p.stroke;
    ctx.strokeRect(-26, lidY, 52, 8);
    strokePath(ctx, [[0, -28], [0, lidY]]);

    ctx.fillStyle = p.detail;
    ctx.fillRect(-28, 4, 56, 24);
    ctx.strokeRect(-28, 4, 56, 24);
    ctx.strokeStyle = p.accent;
    strokePath(ctx, [[-28, 4], [28, 4]]);
    ctx.strokeStyle = p.stroke;
    plinth(ctx, p, 34);
  },

  // Laminated copper/aluminium busbar with terminal lugs.
  busbar: (ctx, p, phase) => {
    ctx.fillStyle = p.body;
    ctx.fillRect(-38, -30, 76, 20);
    ctx.strokeRect(-38, -30, 76, 20);

    ctx.fillStyle = p.accent;
    ctx.fillRect(-34, -4, 68, 12);
    ctx.strokeStyle = p.stroke;
    ctx.strokeRect(-34, -4, 68, 12);
    ctx.fillStyle = p.detail;
    ctx.fillRect(-34, 8, 68, 8);
    ctx.strokeRect(-34, 8, 68, 8);

    const glow = Math.abs(Math.sin(phase * Math.PI * 2));
    for (let i = 0; i < 4; i++) {
      dot(ctx, -24 + i * 16, 2, 3, glow > 0.5 ? p.accent : p.detail);
    }
    plinth(ctx, p, 38);
  },

  // Prismatic cells stood in a receiving rack.
  cell_buffer: (ctx, p) => {
    ctx.fillStyle = p.detail;
    ctx.fillRect(-40, 26, 80, 10);
    ctx.strokeRect(-40, 26, 80, 10);
    for (let i = 0; i < 6; i++) {
      const x = -36 + i * 12.5;
      ctx.fillStyle = p.body;
      ctx.fillRect(x, -22, 9, 48);
      ctx.strokeRect(x, -22, 9, 48);
      ctx.fillStyle = p.accent;
      ctx.fillRect(x + 2, -26, 5, 4);
    }
  },

  // A banded stack of prismatic cells — the cell-to-pack line's work unit.
  cell_stack: (ctx, p) => {
    ctx.fillStyle = p.detail;
    ctx.fillRect(-38, 28, 76, 8);
    for (let i = 0; i < 9; i++) {
      const x = -34 + i * 7.6;
      ctx.fillStyle = p.body;
      ctx.fillRect(x, -24, 6, 52);
      ctx.strokeRect(x, -24, 6, 52);
    }
    // Compression bands top and bottom
    ctx.strokeStyle = p.accent;
    const w = ctx.lineWidth;
    ctx.lineWidth = w * 1.6;
    strokePath(ctx, [[-38, -16], [38, -16]]);
    strokePath(ctx, [[-38, 20], [38, 20]]);
    ctx.lineWidth = w;
    ctx.strokeStyle = p.stroke;
    // End plates
    ctx.fillStyle = p.detail;
    ctx.fillRect(-40, -26, 5, 56);
    ctx.strokeRect(-40, -26, 5, 56);
    ctx.fillRect(35, -26, 5, 56);
    ctx.strokeRect(35, -26, 5, 56);
  },

  // Finished EV pack: cased tray, lid seam, HV terminals and connector.
  pack: (ctx, p) => {
    ctx.fillStyle = p.body;
    ctx.fillRect(-42, -20, 84, 44);
    ctx.strokeRect(-42, -20, 84, 44);
    // Lid seam
    ctx.strokeStyle = p.detail;
    strokePath(ctx, [[-42, -8], [42, -8]]);
    // Internal stack ribs, hinting at the cells inside
    for (let i = 0; i < 7; i++) strokePath(ctx, [[-34 + i * 11, -4], [-34 + i * 11, 20]]);
    ctx.strokeStyle = p.stroke;
    // HV terminals
    ctx.fillStyle = p.accent;
    ctx.fillRect(-26, -26, 12, 7);
    ctx.fillRect(14, -26, 12, 7);
    ctx.strokeRect(-26, -26, 12, 7);
    ctx.strokeRect(14, -26, 12, 7);
    // Service connector
    ctx.fillStyle = p.detail;
    ctx.fillRect(-6, -28, 12, 9);
    ctx.strokeRect(-6, -28, 12, 9);
    // Mounting feet
    ctx.fillStyle = p.detail;
    ctx.fillRect(-38, 24, 12, 6);
    ctx.fillRect(26, 24, 12, 6);
  },

  // Stacked component trays on a dolly.
  tray: (ctx, p) => {
    for (let i = 0; i < 4; i++) {
      const y = -24 + i * 14;
      ctx.fillStyle = i % 2 ? p.detail : p.body;
      ctx.fillRect(-34, y, 68, 11);
      ctx.strokeRect(-34, y, 68, 11);
    }
    ctx.strokeStyle = p.accent;
    strokePath(ctx, [[-34, 32], [34, 32]]);
    ctx.strokeStyle = p.stroke;
    dot(ctx, -24, 38, 4, p.detail);
    dot(ctx, 24, 38, 4, p.detail);
  },

  // Pallet racking, filled to roughly the level the station is holding.
  rack: (ctx, p) => {
    strokePath(ctx, [[-38, -34], [-38, 34]]);
    strokePath(ctx, [[38, -34], [38, 34]]);
    for (let row = 0; row < 3; row++) {
      const y = -30 + row * 22;
      ctx.strokeStyle = p.stroke;
      strokePath(ctx, [[-38, y + 18], [38, y + 18]]);
      ctx.fillStyle = row === 2 ? p.detail : p.body;
      ctx.fillRect(-30, y, 26, 17);
      ctx.strokeRect(-30, y, 26, 17);
      if (row < 2) {
        ctx.fillStyle = p.body;
        ctx.fillRect(4, y, 26, 17);
        ctx.strokeRect(4, y, 26, 17);
      }
    }
    ctx.fillStyle = p.accent;
    ctx.fillRect(-38, 34, 76, 4);
  },

  // Loading bay: roller shutter, dock leveller and bumpers.
  dock: (ctx, p, phase) => {
    ctx.fillStyle = p.body;
    ctx.fillRect(-40, -36, 80, 56);
    ctx.strokeRect(-40, -36, 80, 56);
    // Shutter slats
    ctx.strokeStyle = p.detail;
    for (let i = 0; i < 6; i++) strokePath(ctx, [[-36, -30 + i * 8], [36, -30 + i * 8]]);
    ctx.strokeStyle = p.stroke;
    // Leveller plate
    ctx.fillStyle = p.detail;
    path(ctx, [[-40, 20], [40, 20], [46, 32], [-46, 32]], true);
    ctx.fill();
    ctx.stroke();
    // Bay indicator
    const on = Math.sin(phase * Math.PI * 2) > 0;
    dot(ctx, -30, -42, 4, on ? p.accent : p.detail);
    dot(ctx, 30, -42, 4, on ? p.detail : p.accent);
    // Rubber bumpers
    ctx.fillStyle = p.stroke;
    ctx.fillRect(-42, 8, 5, 12);
    ctx.fillRect(37, 8, 5, 12);
  },

  // 20 ft BESS cabinet: corrugated container with doors and vents.
  container: (ctx, p) => {
    ctx.fillStyle = p.body;
    ctx.fillRect(-44, -24, 88, 48);
    ctx.strokeRect(-44, -24, 88, 48);
    ctx.strokeStyle = p.detail;
    for (let i = 0; i < 9; i++) strokePath(ctx, [[-38 + i * 9.5, -24], [-38 + i * 9.5, 24]]);
    ctx.strokeStyle = p.stroke;
    // Door leaves
    ctx.strokeRect(2, -20, 18, 40);
    ctx.strokeRect(20, -20, 18, 40);
    dot(ctx, 20, 0, 2.5, p.accent);
    // Cooling vent
    ctx.fillStyle = p.accent;
    ctx.fillRect(-38, -16, 22, 4);
    ctx.fillRect(-38, -8, 22, 4);
    // Corner castings
    ctx.fillStyle = p.detail;
    ctx.fillRect(-46, -28, 8, 8);
    ctx.fillRect(38, -28, 8, 8);
    ctx.fillRect(-46, 20, 8, 8);
    ctx.fillRect(38, 20, 8, 8);
  },

  // Liquid cold plate: serpentine coolant channel across a plate.
  coldplate: (ctx, p, phase) => {
    ctx.fillStyle = p.body;
    ctx.fillRect(-40, -26, 80, 52);
    ctx.strokeRect(-40, -26, 80, 52);

    ctx.strokeStyle = p.accent;
    const w = ctx.lineWidth;
    ctx.lineWidth = w * 1.8;
    ctx.beginPath();
    ctx.moveTo(-32, -18);
    for (let i = 0; i < 4; i++) {
      const y = -18 + i * 12;
      ctx.lineTo(32, y);
      ctx.lineTo(32, y + 6);
      ctx.lineTo(-32, y + 6);
      ctx.lineTo(-32, y + 12);
    }
    ctx.stroke();
    ctx.lineWidth = w;
    ctx.strokeStyle = p.stroke;

    const flow = Math.abs(Math.sin(phase * Math.PI * 2));
    dot(ctx, -32, -18, 3 + flow * 1.5, p.accent);
    ctx.fillStyle = p.detail;
    ctx.fillRect(-44, -30, 10, 8);
    ctx.fillRect(34, 22, 10, 8);
  },

  // Quarantine bin, lidded and hazard-striped.
  reject: (ctx, p) => {
    ctx.fillStyle = p.body;
    path(ctx, [[-30, -12], [30, -12], [24, 30], [-24, 30]], true);
    ctx.fill();
    ctx.stroke();
    ctx.fillStyle = p.detail;
    ctx.fillRect(-34, -22, 68, 10);
    ctx.strokeRect(-34, -22, 68, 10);

    ctx.strokeStyle = p.accent;
    const w = ctx.lineWidth;
    ctx.lineWidth = w * 1.6;
    for (let i = 0; i < 4; i++) strokePath(ctx, [[-24 + i * 14, 26], [-14 + i * 14, 2]]);
    ctx.lineWidth = w;
    ctx.strokeStyle = p.stroke;
  },
};

/**
 * Draws `kind` centred on (cx, cy) at `size` pixels across.
 *
 * `phase` (0 → 1, repeating) animates the moving part. Pass a constant for a
 * station that is not running, so motion on the floor always means work.
 */
export function drawEquipmentGlyph(
  ctx: CanvasRenderingContext2D,
  kind: EquipmentKind,
  cx: number,
  cy: number,
  size: number,
  palette: GlyphPalette,
  phase = 0
): void {
  const glyph = GLYPHS[kind] ?? GLYPHS.robot_arm;
  ctx.save();
  ctx.translate(cx, cy);
  ctx.scale(size / 100, size / 100);
  ctx.strokeStyle = palette.stroke;
  ctx.fillStyle = palette.body;
  ctx.lineWidth = 3.5;
  ctx.lineJoin = 'round';
  ctx.lineCap = 'butt';
  glyph(ctx, palette, phase);
  ctx.restore();
}

/** Short human name for the equipment, used in the inspector panel. */
export const EQUIPMENT_LABELS: Record<EquipmentKind, string> = {
  robot_arm: 'Articulated robot',
  gantry: 'Gantry crane',
  laser: 'Laser station',
  plasma: 'Plasma cleaner',
  press: 'Hydraulic press',
  vision: 'Vision inspection',
  tester: 'Test instrument',
  cycler: 'Battery cycler',
  sorter: 'Diverter gateway',
  dispenser: 'Dispensing head',
  fastener: 'Nutrunner spindle',
  harness: 'Harness station',
  controller: 'BMS controller',
  seal: 'Cover & seal press',
  busbar: 'Busbar assembly',
  cell_buffer: 'Cell rack',
  cell_stack: 'Cell stack buffer',
  pack: 'Pack buffer',
  tray: 'Tray stack',
  rack: 'Pallet racking',
  dock: 'Loading dock',
  container: 'BESS container',
  coldplate: 'Cold plate station',
  reject: 'Quarantine bin',
};
